title       = "cmo"
baseURL     = "https://mathchina-cli.tamnd.com/"
description = "Browse Chinese math competition problems from mathchina.com"
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/mathchina-cli"
